# Generated by Django 6.0 on 2025-12-23 10:58

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1), validators=[app.models.validate_age_7]),
        ),
    ]
