# Generated by Django 6.0 on 2025-12-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_file_module_image_module_text_module_video_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=2, upload_to='videos/', verbose_name='Video File'),
            preserve_default=False,
        ),
    ]
