# Generated by Django 6.0 on 2025-12-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_video_url_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
