# Generated by Django 6.0 on 2025-12-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_video_video_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=2, upload_to='videos/', verbose_name='Video File'),
            preserve_default=False,
        ),
    ]
